services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nibiru-backend
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    container_name: nibiru-postgres
    restart: always
    environment:
      POSTGRES_USER: nibiru
      POSTGRES_PASSWORD: nibiru
      POSTGRES_DB: nibiru
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nibiru-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: